import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className="min-h-screen antialiased relative"
            >
                {/* 🔥 TEXTURE OVERLAY ABOVE EVERYTHING */}
                <div
                    className="fixed inset-0 pointer-events-none z-[99]"
                    style={{
                        backgroundImage: 'url("/assets/paper.svg")',
                        backgroundRepeat: "repeat",
                        backgroundSize: "500px",
                        opacity: 0.0,      // adjust how strong texture appears
                    }}
                />

                {/* PAGE CONTENT BELOW OVERLAY */}
                <div className="relative z-[1]">
                    {children}
                </div>

            </body>
        </html>
    );
}
