import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased relative`}
            >
                {/* 🔥 PAPER TEXTURE OVERLAY - COVERS ENTIRE WEBSITE */}
                <div
                    className="fixed inset-0 pointer-events-none z-[99]"
                    style={{
                        backgroundImage: 'url("/assets/pp.png")',
                        backgroundRepeat: "no-repeat",
                        backgroundSize: "cover",
                        opacity: 0.65,      // strong paper texture
                        mixBlendMode: "multiply", // creates authentic paper texture
                        filter: "contrast(1.1) brightness(0.98)", // enhances texture visibility
                    }}
                />

                {/* PAGE CONTENT BELOW OVERLAY */}
                <div className="relative z-[1]">
                    {children}
                </div>

            </body>
        </html>
    );
}
